### ISSUE TITLE
Production app crashes on android: [Fatal Exception: java.lang.NoSuchFieldError]

### ISSUE THREAD

**Issue by supmanyu** [mdrajibsk8/react-native-device-number#14]
I've been getting reports of the app crashing whenever the library is triggered from the react-native side. Attaching the firebase crashlytics error trace below:
```js
Fatal Exception: java.lang.NoSuchFieldError: No field CREDENTIALS_API of type Lcom/google/android/gms/common/api/Api; in class Lcom/google/android/gms/auth/api/Auth; or its superclasses (declaration of 'com.google.android.gms.auth.api.Auth' appears in /data/app/~~P9ZvDb0sekwXPMrz-zK69A==/com.package.name-7N6gBzn7zT2bR5O-36inUg==/base.apk!classes2.dex)
       at com.reactlibrary.devicenumber.DeviceNumberActivity.a(DeviceNumberActivity.java:1)
       at com.reactlibrary.devicenumber.DeviceNumberActivity.onCreate(DeviceNumberActivity.java:3)
       at android.app.Activity.performCreate(Activity.java:8422)
       at android.app.Activity.performCreate(Activity.java:8395)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3845)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4014)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8423)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

Environment
`react-native: 0.68.5`

**Comment by AjayGol** [comment]
same issue i have get

**Comment by Nitish33** [comment]
Just add this line in your app/build.gradle file, and it should work
`configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.google.android.gms' &&
                details.requested.name == 'play-services-auth') {
            details.useVersion '20.7.0'
        }
    }
}
`

Basically we are forcing this library to use slightly older version of `play-service-auth` as v21.0.0 of  `play-service-auth` has introduced some breaking changes
https://developers.google.com/android/guides/releases#february_15_2024

**Comment by sulaimaan26** [comment]
When this will be fixed Any ETA please

**Comment by supmanyu** [comment]
@Nitish33 thanks for the workaround, but its not really a fix as Google might stop accepting builds with older versions of `play-services-auth`

**Comment by mdrajibsk8** [comment]
Kindly check the new version(v1.0.9) and do let me know if it fixes the issue. thanks

**Comment by supmanyu** [comment]
@mdrajibsk8 still crashing for us with the newer `play-services-auth` versions

**Comment by sulaimaan26** [comment]
Still the issue occurs

**Comment by mdrajibsk8** [comment]
Please share your package.json and both build.gradle file so I can have a look into that @supmanyu 
If you have any problem share the build.gradle file, you can share the screenshot of the play services in both of the files. thanks

**Comment by tuanlam92** [comment]
Same issue.
